### ISSUE TITLE
ff won't compile on RHEL 7.5

### ISSUE THREAD

**Issue by cfaber** [stsaz/ff#1]
``
../ff/FF/data/ffutf8.c: In function ‘ffutf8_to_utf16’:
../ff/FF/data/ffutf8.c:435:25: error: ‘n’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   if (!ffutf16_basic(n) || n > 0xffff)
                         ^
../ff/FF/data/ffutf8.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make: *** [ff-obj/ffutf8.o] Error 1
``

**Comment by stsaz** [comment]
To work-around these compiler errors remove `-Werror` & `-Wno-implicit-fallthrough` from `ff/makerules` file.  I don't have older compiler versions on my machine, so I can't resolve them.  But the first particular warning can be resolved by using `uint n = 0;` within this function, though I don't see how `n` can be uninititialized when used at line 435.  Maybe it's just an older compiler's false assumption.
